json.id carted_product.id
json.user_id carted_product.user_id
json.product_id carted_product.product_id
json.product carted_product.product
json.order carted_product.order
json.user carted_product.user
json.quantity carted_product.quantity
json.status carted_product.status
json.order_id carted_product.order_id
json.created_at carted_product.created_at
json.updated_at carted_product.updated_at
