json.id product.id
json.product product.product
json.name product.name
json.price product.price
json.tax product.tax
json.total product.total
json.is_discounted? product.is_discounted?
json.description product.description
json.image_url product.image_url
json.inventory product.inventory
